name: Run-WF-Build-By-WF-Core-Trigger

on:
  repository_dispatch:
    types: [wf-core-owasp-trigger]
    
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: dependency-check-wf-core
          token: ${{ secrets.TRIGGER_KEY }}

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Build with Maven
        run: 
          mvn -B package --file pom.xml
          ls -la ${{github.workspace}}
          ls -la ${{github.workspace}}/reports
          ls -la ~/.m2
          
      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: dependency-check-wf
        with:
          project: 'wf-core-gha'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: dependency-check-wf-core
          path: ${{github.workspace}}/reports
